apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: lokioutput
spec:
  loki:
    url: http://loki.loki.svc.cluster.local:3100
    configure_kubernetes_labels: true
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
