{
 "title": "Track FA metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "VM Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VM read average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "max_over_time(vsphere_vm_virtualDisk_read_average{clustername=\"RaceTeam\", disk!=\"instance-total\"}[$__interval])",
     "legendFormat": "{{source}}-{{disk}}"
    }
   ]
  },
  {
   "title": "VM write average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "max_over_time(vsphere_vm_virtualDisk_write_average{clustername=\"RaceTeam\", disk!=\"instance-total\"}[$__interval])",
     "legendFormat": "{{source}}-{{disk}}"
    }
   ]
  },
  {
   "title": "VM Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max_over_time(vsphere_vm_virtualDisk_numberReadAveraged_average[$__interval])",
     "legendFormat": "{{guesthostname}}-{{disk}}"
    }
   ]
  },
  {
   "title": "VM Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max_over_time(vsphere_vm_virtualDisk_numberWriteAveraged_average[$__interval])",
     "legendFormat": "{{guesthostname}}-{{disk}}"
    }
   ]
  },
  {
   "title": "VM Read Outstanding IO (queue depth?)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max_over_time(vsphere_vm_virtualDisk_readOIO_latest[$__interval])",
     "legendFormat": "{{guesthostname}}-{{disk}}"
    }
   ]
  },
  { "title": "ESXi Host Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Host Reads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(host) (max_over_time(purefa_host_performance_bandwidth_bytes{dimension=\"read_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Writes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(host) (max_over_time(purefa_host_performance_bandwidth_bytes{dimension=\"write_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Reads IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by(host) (max_over_time(purefa_host_performance_throughput_iops{dimension=\"reads_per_sec\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum by(host) (max_over_time(purefa_host_performance_throughput_iops{dimension=\"writes_per_sec\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Volume Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Volume Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max_over_time(purefa_volume_performance_bandwidth_bytes{dimension=\"read_bytes_per_sec\"}[$__interval])",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Volume Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max_over_time(purefa_volume_performance_bandwidth_bytes{dimension=\"write_bytes_per_sec\"}[$__interval])",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Volume Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "max_over_time(purefa_volume_performance_throughput_iops{dimension=\"reads_per_sec\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "max_over_time(purefa_volume_performance_throughput_iops{dimension=\"writes_per_sec\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Volume Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max_over_time(purefa_volume_performance_average_bytes{dimension=\"bytes_per_op\"}[$__interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Array Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Array Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(dimension) (max_over_time(purefa_array_performance_bandwidth_bytes{dimension=~\"write_bytes_per_sec|read_bytes_per_sec\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Array Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(max_over_time(purefa_array_performance_throughput_iops{dimension=\"reads_per_sec\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Array Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "sum(max_over_time(purefa_array_performance_throughput_iops{dimension=\"writes_per_sec\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg bytes per write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_average_bytes{dimension=\"bytes_per_write\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg bytes per read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_average_bytes{dimension=\"bytes_per_read\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg bytes per op",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(purefa_array_performance_average_bytes{dimension=\"bytes_per_op\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Array Read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{dimension=\"usec_per_read_op\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Array Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(purefa_array_performance_latency_usec{dimension=\"usec_per_write_op\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}