kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: minio-tenant-source
  name: account-minio-tenant-source-manager-mqich

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: minio-tenant-source
  name: role-minio-tenant-source-manager-mqich
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-minio-tenant-source-manager-mqich
  namespace: minio-tenant-source
subjects:
- kind: ServiceAccount
  name: account-minio-tenant-source-manager-mqich
  namespace: minio-tenant-source
roleRef:
  kind: Role
  name: role-minio-tenant-source-manager-mqich
  apiGroup: rbac.authorization.k8s.io
